### ISSUE TITLE
Gulpfile rev task dontRenameFiles

### ISSUE THREAD

**Issue by kube** [42Zavattas/generator-bangular#12]
Not a big issue, but not really clean :

```
gulp.task('rev', function () {

  var revAll = new $.revAll({
    dontRenameFile: ['index.html', 'favicon.ico'],
    transformFilename: function (file, hash) {
      var filename = path.basename(file.path);
      if (filename === 'index.html' || filename === 'favicon.ico') {
        return filename;
      }
```

I don't understand if `dontRenameFile` is used anywhere.

**Comment by Apercu** [comment]
Yeah definitely, seems pretty strange to me that ignored files weren't copied at all and that was the only "trick" that worked at the time, will fix this right away! I'll make a PR if I can.

Thanks for your input!
