### ISSUE TITLE
restructure client folder

### ISSUE THREAD

**Issue by Tallyb** [42Zavattas/generator-bangular#19]
You have a good generator, but it still needs some tweeks to make it a world class. 
for example: 
According to commonly used angular style guide the suggested structure of the client folder should be 
client \app \ components
client \app\feature1 (views, controllers, services...)
client \app\feature2 (views, controllers, services...)
client \ assets

This will reduce the need for "files to inject".

**Comment by brunowego** [comment]
+1

**Comment by meriadec** [comment]
This idea is interesting, and could fit to some projects. On the other hand, it may also over-complicate the components (routes, services..) generation, as it will have to ask everytime in which feature you want to put it (and keep a track on already created features, etc.).

I do not handle to imagine a simple way to implement it (even as an "optional style"). If you got some implementation ideas that does not break the current generation workflow it could be great.

**Comment by Tallyb** [comment]
The way I envision it is having a generator asking for yo bangular:filter <name>. It will create filter directory under directory <name> . If directory name already exist, it will use the existing one. As such if you are creating a feature <things> and you generate yo bangular:filter thing, you will get thing\filter. When later adding yo bangular:directive thing the folder thing\directives will be generated. (everything under client\app, of course) Do you see an issue with that?

**Comment by Apercu** [comment]
@Tallyb  As @meriadec said, it will require a *lot* of refactor of the code to do it and might break a lot of things. I think it might require to create another generator, since it doesn't fit all people needs.

Would love to see a PR on this, but since no one seems interested to do it, I'll close this issue for now. Feel free to reopen otherwise.
