### ISSUE TITLE
use gulp-load-plugins

### ISSUE THREAD

**Issue by Tallyb** [42Zavattas/generator-bangular#20]
You can remove a lot of code by using the gulp-load-plugins package. 
var gulpLoadPlugins = require('gulp-load-plugins');
var $ = gulpLoadPlugins();
and then you use $.<plugin name minus gulp> and avoid the requires such as 
var autoprefixer         = require('gulp-autoprefixer');
will be $.autoprefixer

https://www.npmjs.com/package/gulp-load-plugins

**Comment by Apercu** [comment]
It has been removed in https://github.com/42Zavattas/generator-bangular/commit/0e284160c87491a37824526fa0a1c87cada4c63a, since it doesn't bring much to the project, we don't mind writing some requires because the tasks are separated and it helps to see exactly what's used in each file.

**Comment by Tallyb** [comment]
You can still achieve this by looking for the $. sign, but it is your project...

**Comment by Apercu** [comment]
For research purposes I've done a little comparative of lines with and without *gulp-load-plugins*

#### With

| File                       | Lines       |
| ------------------------ |-------------|
| ./tasks/build.js       | 10          |
| ./tasks/chore.js      | 1           |
| ./tasks/control.js    | 2           |
| ./tasks/chore.js      | 1           |
| ./tasks/sass.js       | 1           |
| ./tasks/serve.js      | 2           |
| ./tasks/test.js         | 3           |
| ./tasks/watch.js      | 4           |
| **Total**                | 24          |

#### Without

| File                                                                                                                                   | Lines       |
| ----------------------------------------------------------------------------------------------------------------- |-------------|
| ./package.json                                                                                                                  | 1            |
| ./node_modules/gulp-load-plugins/index.js                                                                      | 111        |
| ./node_modules/gulp-load-plugins/node_modules/node-findup-sync/lib/findup-sync.js  | 50          |
| ./node_modules/gulp-load-plugins/node_modules/multimatch/index.js                           | 31          |
| **Total**                                                                                                                           | 193         |

It was really useful when we have only one gulpfile to help us not writing 26 requires, but as I said its usefulness has been greatly diminished by the task refactor, and thus was no longer needed.

**Comment by Tallyb** [comment]
point taken (although you could argue similarly for any plugin)
