### ISSUE TITLE
`gulp preview` broken.

### ISSUE THREAD

**Issue by MichaelJCole** [42Zavattas/generator-bangular#22]
Installed to test.  `gulp preview` and it just shows "test" (the name of my app).

Looking in the console, got this error:

    Uncaught SyntaxError: Failed to execute 'querySelector' on 'Document': '[ng-app.ec793650]' is not a valid selector.

`gulp` served the app, but it wasn't styled (maybe intentionally).

**Comment by Apercu** [comment]
This bug has been introduced by [this commit](https://github.com/smysnk/gulp-rev-all/commit/056baae48d458391f173c0a1b2e8740f954fa36b) on the `gulp-rev-all` package. Until we find a way to work this out, either by finding what's need to be fixed on our side, or by inform the repo owners that there is a problem, you should be able to get rid of the problem by downgrading to the `0.8.18` of the package

    npm install --save-dev gulp-rev-all@0.8.18

**Comment by Apercu** [comment]
The `0.11.2` release of Bangular now locks the version of `gulp-rev-all` to prevent the issue.

**Comment by MichaelJCole** [comment]
Cool, thanks!
