### ISSUE TITLE
Missing dependancy: Selenium

### ISSUE THREAD

**Issue by jmsherry** [42Zavattas/generator-bangular#23]
Hi, when you run gulp e2e you get 'Error: No selenium server jar found at the specified location'. Is there a preferred npm package to be installed?? I just wondered if there was any chance of docs guidance or maybe getting it set as a dependancy somewhere in the boilerplate?

Thanks, and great work. :)

**Comment by Apercu** [comment]
Have you run the `gulp e2e:update` command?

**Comment by jmsherry** [comment]
I hadn't. Thanks for that. I'm getting some other errors to do with the inclusion of ng-route, but this solves the immediate issue for me.
