### ISSUE TITLE
Failed to load CSS

### ISSUE THREAD

**Issue by techguysid** [42Zavattas/generator-bangular#26]
I have few modules other than the signup login and home for eg : ABC. I have ABC.scss file which has a few css styling to div elements in ABC.html.But on running gulp the project fails to load and it shows error parsing app.css file.
I have @injected the ABC.scss file in app.scss file.Please help

**Comment by meriadec** [comment]
It's difficult to help without seeing the code, anyway you can try to generate a new route with `yo bangular:route newRoute`, answer `yes` to the scss file creation question, and analyze how it's imported into app.scss.

**Comment by techguysid** [comment]
I have created the route using the same command.
abc.html -
 <div class="start" ng-if="Auth.isLogged()">
     <a href="/blahblah"> <button>Start</button></a>
 </div> 

abc.scss -
/**
 * home.scss
 */
.start {
	background-color:red;
}
app.scss
@import "../views/abc/abc";

and after this when I gulp .. app.css is generated in a css folder inside styles so far so good.
app.css (generated on runtime)
/**
 * home.scss
 */
.start {
  background-color: red; }
 and then comes the error - Error in parsing "app.css" Unexpected token "." on line 4

**Comment by Apercu** [comment]
Have you a public example of this? I'm not able to reproduce.

**Comment by Apercu** [comment]
Closing since no response from OP, please reopen if you're still experiencing the issue and able to give us a demo project to work with, your example seems fine to me.
