### ISSUE TITLE
update `del` to 2.0.2 breaks build

### ISSUE THREAD

**Issue by johnwebbcole** [42Zavattas/generator-bangular#29]
If you upgrade `del` from 1.1.1 to 2.0.2 the build breaks.  It appears that `del` changed from a callback to a promise format.

The fix is easy, in `task/build.js` change clean:dist and clean:finish to:

```js
gulp.task('clean:dist', function (done) {
  del(['dist/**', '!dist', '!dist/.git{,/**}']).then(function (paths) {
    done();
  });
});

gulp.task('clean:finish', function (done) {
  del([
    '.tmp/**',
    'dist/client/app.{css,js}'
  ].concat(toDelete)).then(function (paths) {
    done();
  });
});
```

**Comment by Apercu** [comment]
Hi, thanks for this :)
I'll update many dependencies of the project soon. Kinda strange they didn't keep the callback support, it's better in my opinion used with gulp, but whatever
