### ISSUE TITLE
Update karma.conf to be run standalone

### ISSUE THREAD

**Issue by meriadec** [42Zavattas/generator-bangular#3]
Actually, karma tests are run via `gulp test`, and use files defined in gulpfile.js ([here](https://github.com/42Zavattas/generator-bangular/blob/develop/app/templates/gulpfile.js#L157)).

The problem is that running karma standalone, for example with Webstorm integrated karma runner, use only karma.conf.js ([here](https://github.com/42Zavattas/generator-bangular/blob/develop/app/templates/client/%23karma.conf.js)) which does not define any file path to test, and result into an empty test suite.

Two solutions:

- duplicate files from gulpfile.js into karma.conf.js
- describe files only on karma.conf.js and read it as json in gulpfile

what dyou think

**Comment by Apercu** [comment]
Totally agree on that, was thinking of it at first but with all the other work to do besides I've put it away, but now we should look into this, definitely.

**Comment by Kerumen** [comment]
Duplicating is a bad idea so I think the best option would be to describe the files in karma.conf.js and read the it in the gulpfile.
