### ISSUE TITLE
Watcher fails sometimes when files are added or updated.

### ISSUE THREAD

**Issue by camomiles** [42Zavattas/generator-bangular#30]
Good afternoon,

When I edit html and sass files in the project build by bangular-generator,
gulp watching sometimes fails with the following error in the minimatch module and stops watching files:

![screen shot 2015-10-08 at 11 37 36 am](https://cloud.githubusercontent.com/assets/3336228/10355578/0a78124c-6db1-11e5-8763-15f94e3fb7f4.png)

How can I fix it to update files properly and don't fail?

Thanks.

**Comment by Apercu** [comment]
Can you please give us your version of bangular you can check in the `.yo-rc.json`?

Your error seems to have been addressed in [this PR](https://github.com/42Zavattas/generator-bangular/pull/28).

Can you try this fix?

**Comment by camomiles** [comment]
Hello, 

The version of bangular generator inside .yo-rc.json is "0.11.2", I got it from running install commands from readme file, so I guess it is the latest version in npm repository.

Removing those lines from watch.js task seems to do the trick, thanks for your help!

**Comment by Apercu** [comment]
Hi,

Glad you got it working.
I just noticed the latest 0.11.3 version was not published to npm, thanks for the heads-up!
