### ISSUE TITLE
Index.html references non-optimised scripts in gulp preview

### ISSUE THREAD

**Issue by jmsherry** [42Zavattas/generator-bangular#32]
I feel like I might be tired and missing something here but when I do `gulp preview` on a newly scaff'd project the index.html references the scripts in the client dir, not the dist dir.

Am I doing something wrong?

**Comment by meriadec** [comment]
Hey, thanks for this, we effectively had a bad configuration of `gulp-open` in the `preview` task.
Can you try the fix and tell us if it works now ?

**Comment by jmsherry** [comment]
Hi guys,
I've made these changes and they work. ;)

Thanks

**Comment by meriadec** [comment]
Cool, we'll update the master branch soon
