### ISSUE TITLE
Unexpected token e

### ISSUE THREAD

**Issue by jmsherry** [42Zavattas/generator-bangular#37]
Hi guys,
Trying again. Re-installed the generator and scaffolded, saying yes to everything but socket support. When I run gulp and the page loads I get:

```
angular.js:1075 Uncaught SyntaxError: Unexpected token e
fromJson @ angular.js:1075
get @ angular-cookies.js:173
(anonymous function) @ auth.js:9
invoke @ angular.js:4219
instantiate @ angular.js:4227
(anonymous function) @ angular.js:4088
invoke @ angular.js:4219
enforcedReturnValue @ angular.js:4072invoke @ angular.js:4219(anonymous function) @ angular.js:4037getService @ angular.js:4178invoke @ angular.js:4210(anonymous function) @ angular.js:4041forEach @ angular.js:326createInjector @ angular.js:4041doBootstrap @ angular.js:1455bootstrap @ angular.js:1476angularInit @ angular.js:1370(anonymous function) @ angular.js:26446trigger @ angular.js:2773eventHandler @ angular.js:3047
```

Does this happen for you?

Thanks

**Comment by vrebierr** [comment]
Try to remove cookies

**Comment by Apercu** [comment]
Have you deleted your cookies before?

**Comment by jmsherry** [comment]
Geezas! I'm so sorry guys! :D I feel like I'm on a never ending merry-go-round trying to get all the technologies in my project to play together. I keep come finding the same issue but it's weeks later, and I've forgotten by then... 

Sorry, and thanks...

**Comment by meriadec** [comment]
:smile_cat:
