### ISSUE TITLE
Added this project to comparison of starters

### ISSUE THREAD

**Issue by dancancro** [42Zavattas/generator-bangular#6]
Hi everyone,

I have added this project to my collection of such things:
[Comparison of Angular app Starters](http://www.dancancro.com/comparison-of-angularjs-application-starters)

If you would like to help fill in the details about it, let me know and I will add you to the editor list.  You'll be helping to save people countless hours researching the complex trade-offs among all these options.

Kind regards,
Dan

**Comment by meriadec** [comment]
Hi Dan, we really appreciate it, this will help our project to gain visibility, and we will be ok for helping fill the comparisons criterias.

let's get in touch

**Comment by Apercu** [comment]
Thanks for everything, we will carry on improving the spreadsheet to update bangular information's.

Have a good day!
