### ISSUE TITLE
Use autoprefixer in build process

### ISSUE THREAD

**Issue by meriadec** [42Zavattas/generator-bangular#9]
It's a pain but someone told me some people aren't using Chrome as their browser.
So... *maybe* we *should* considerate using [gulp-autoprefixer](https://github.com/sindresorhus/gulp-autoprefixer) while building app.

**Comment by Apercu** [comment]
You mean by default? We don't know the speed impacts of this yet, but since you've assigned this to the 0.10 I guess that not a consideration anymore?
